### ISSUE TITLE
What's with that margin ? 

### ISSUE THREAD

**Issue by Sshuichi** [talpor/django-dashing#41] opened 2015-11-17 12:09 UTC
Where does this margin-right come from ? 
![margin](https://cloud.githubusercontent.com/assets/5939429/11210987/05c51b7c-8d24-11e5-81dd-0ba1e3fdf6e9.png)

**Comment by individuo7** [comment] 2016-01-04 03:15
I can't reproduce it, I just released a new versión then I will close this issue

**Closed by individuo7** 2016-01-04 03:15 UTC
